## DataFrames

In [1]:
# Returns a DataFrame (df)
import nsfg
df = nsfg.ReadFemPreg()
df

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,8.8125
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,7.8750
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,9.1250
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,7.0000
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,6.1875
5,6,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.5625
6,6,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,9.5625
7,6,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.3750
8,7,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,7.5625
9,7,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,6.6250
10,12,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3612.781968,4146.013572,6909.331618,1,31,NaN,7.8125
11,14,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,7.0000
12,14,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,4.0000
13,14,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,NaN
14,15,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,NaN
15,15,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.6875
16,15,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.5000
17,18,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,6.3125
18,18,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,NaN
19,21,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.7500
20,21,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.1875
21,23,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,5.5625
22,23,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,NaN
23,24,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.7500
24,24,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,7.3750
25,24,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.8125
26,28,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3407.794208,3808.343516,6949.846082,2,57,NaN,8.1250
27,31,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.1250
28,31,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,6.0625
29,31,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.4375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13563,12547,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6875
13564,12547,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6250
13565,12550,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3080.452699,3745.326058,5268.550165,1,79,NaN,8.1250
13566,12551,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2418.538866,3653.453268,3951.940400,2,75,NaN,7.5000
13567,12554,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13568,12554,2,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13569,12556,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13570,12556,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.6875
13571,12556,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.0000
13572,12556,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13573,12561,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.5625
13574,12561,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.1250
13575,12564,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1820.850938,2129.214067,2768.191208,2,44,NaN,NaN
13576,12565,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,6.4375
13577,12565,2,35.0,1.0,8.0,NaN,NaN,NaN,NaN,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,NaN
13578,12566,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,6.0000
13579,12566,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,7.0000
13580,12568,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13581,12568,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,6.3750
13582,12568,3,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13583,12569,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,NaN
13584,12569,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,6.3750
13585,12570,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13586,12570,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13587,12570,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13588,12571,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,6.1875
13589,12571,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13590,12571,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13591,12571,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000
13592,12571,5,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000

In [2]:
# Returns sequence of column names as Unicode strings
# Result is an Index, another Pandas data structure
df.columns

Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'laborfor_i', 'religion_i', 'metro_i', 'basewgt', 'adj_mod_basewgt',
       'finalwgt', 'secu_p', 'sest', 'cmintvw', 'totalwgt_lb'],
      dtype='object', length=244)

In [3]:
# Can be treated like a list
df.columns[1]

'pregordr'

In [4]:
# Access a column from a df by using column name as a key
pregordr = df['pregordr']
# OR using dot notation
# pregordr = df.pregordr
# notation only works if column name is valid Python identifier
# so it has to begin with a letter, can't contain spaces, etc.

type(pregordr)

pandas.core.series.Series

In [5]:
# Series is another Pandas structure.
# It's like a Python list with additional features such as
# indices and corresponding values
pregordr

0        1
1        2
2        1
3        2
4        3
5        1
6        2
7        3
8        1
9        2
10       1
11       1
12       2
13       3
14       1
15       2
16       3
17       1
18       2
19       1
20       2
21       1
22       2
23       1
24       2
25       3
26       1
27       1
28       2
29       3
        ..
13563    2
13564    3
13565    1
13566    1
13567    1
13568    2
13569    1
13570    2
13571    3
13572    4
13573    1
13574    2
13575    1
13576    1
13577    2
13578    1
13579    2
13580    1
13581    2
13582    3
13583    1
13584    2
13585    1
13586    2
13587    3
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, Length: 13593, dtype: int64

In [6]:
# Variable name, Series length, and data type
# int64 is a type provided by NumPy
# if it's run on 32bit maching, you might see
# int32

# Access elements of Series using integer indicies and slices
pregordr[0]

1

In [7]:
# result of slice is another Series
pregordr[2:5]

2    1
3    2
4    3
Name: pregordr, dtype: int64

## Variables

* __caseid__ integer ID of the respondent
* __prglength__ integer duration of the pregnancy in weeks
* __outcome__ integer code for the outcome of the pregnancy.  Code 1 = live birth
* __pregordr__ pregnancy serial number.  1st preg = 1, 2nd preg = 2
* __birthord__ serial number for live births 1st live birth = 1 etc.  If no live births, it's blank
* __birthwgt\_lb__ and __birthwgt\_oz__ contain pounds and ounces parts of the birth weight of the baby
* __agepreg__ age of mother at end of pregnancy
* __finalwgt__ statistical weight associated with respondant.  Floating point value indicates number of people in Us population this respondent represents

## Transformation

In [8]:
# Data cleaning

# def CleanFemPreg(df):
#     df.agepreg /= 100.0  # integer number of centiyears, converting to float in years
#     
#     na_vals = [97, 98, 99] # special codes for 97=Not Ascertained, 98=Refused, and 99=Don't Know
#     df.birthwgt_lb.replace(na_vals, np.nan, inplace=True) # Replace with NaN (Not A Number)
#     df.birthwgt_oz.replace(na_vals, np.nan, inplace=True) # Replace with NaN (Not A Number)
#     
#     df['totalwgt_lb'] = df.birthwgt_lb + df.birthwgt_oz / 16.0 # Creates new column combining total weight

### NOTE ###
# When adding new columns, MUST use dictionary syntax, not dot notation
### CORRECT ###
#    df['totalwgt_lb'] = df.birth...
### WRONG! ###
#    df.totalwgt_lb = df.birth...

In [10]:
# If either argument is NaN, numpy returns NaN
import numpy as np
np.nan / 100.0

nan

## Validation

In [13]:
# Just make sure things add up especially when exporting/importing from different environments

# NSFG codebook has tables to summarize each variable
# Table for OUTCOME, encoding outcome of each pregnancy

# value  label       Total
# 1 Live Birth       9148
# 2 Induced Abortion 1862
# 3 Stillbirth        120
# 4 Miscarriage      1921
# 5 Ectopic Pregnancy 190
# 6 Current Pregnancy 352

# Series class provides value_counts
# counts number of times each value appears
# Compare with published data

df.outcome.value_counts().sort_index()
# value_counts is a series
# sort_index sorts Series by index

1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: outcome, dtype: int64

In [16]:
# value  label    Total
# . Inapplicable  4449
# 0-5 -6 Pounds   1125
# 6 6 Pounds      2223
# 7 7 Pounds      3049
# 8 8 Pounds      1889
# 9-95 9+ Pounds   799

df.birthwgt_lb.value_counts(sort=False)

8.0     1889
7.0     3049
6.0     2223
4.0      229
5.0      697
10.0     132
12.0      10
14.0       3
3.0       98
1.0       40
2.0       53
0.0        8
9.0      623
11.0      26
13.0       3
15.0       1
Name: birthwgt_lb, dtype: int64

In [17]:
# Supposed to have a 51lb baby.  It's an error.

# expression in [] yields a Series of type bool
# where True indicates the condition is true
# When bool used as index, it selects only 
# elements that satisfy the condition

# line added to def CleanFemPreg
# df.birthwgt_lb[df.birthwgt_lb > 20] = np.nan

## Interpretation

Think on 2 levels at the same time:

1. level of Statistics

2. level of Context

In [23]:
def MakePregMap(df):
    d = defaultdict(list)
    for index, caseid in df.caseid.interitems():
        d[caseid].append(index)
    return d

# df = DataFrame with preg data
# interitems = enumerates index (row numbers) and caseid for each pregnancy
# d = dictionary that maps from each caseID to list of indices.
# 'defaultdict' is in Python 'collections' module

NameError: name 'defaultdict' is not defined

In [22]:
caseid = 10229
indices = preg_map[caseid]
df.outcome[indices].values

NameError: name 'preg_map' is not defined